#ifndef __CODECDEFINE_H__
#define __CODECDEFINE_H__


#define IMG_FORMAT_NV12 "NV12"
#define IMG_FORMAT_NV21 "NV21"
#define IMG_FORMAT_YUV422_YUYV "YUYV"
#define IMG_FORMAT_YUV422_YVYU "YVYU"
#define IMG_FORMAT_YUV422_UYVY "UYVY"
#define IMG_FORMAT_YUV422_VYUY "VYUY"
#define IMG_FORMAT_BGR888 "BGR888"
#define IMG_FORMAT_RGB888 "RGB888"






#endif //__CONFIG_H__

